# Generated by Django 4.1.3 on 2022-12-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_datac_completed_task_data_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='data_completed',
        ),
        migrations.AddField(
            model_name='task',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
